# Permalinks
#
permalink:           /:categories/:title

# Setup
title:               Ben's Blog 
tagline:             'A place to share my thoughts'
description:         'Description Todo...'
url:                 https://benscabbia.github.io 
baseurl:            '' 
paginate:            5

# About/contact
author:
  name:              Benjamin Scabbia 
  url:               https://benjaminscabbia.co.uk
  email:             benscabbia@gmail.com

# Custom vars
version:             1.0.0

# Plugins
plugins:
  - jekyll-paginate

