# Permalinks
#
permalink:           /:categories/:title

# Setup
title:               Ben's Blog 
tagline:             'A place to share my thoughts'
description:         Ben's Blog
url:                 https://benscabbia.co.uk 
baseurl:             '' 
paginate:            5

# About/contact
author:
  name:              Benjamin Scabbia 
  url:               https://benscabbia.co.uk
  email:             benscabbia@gmail.com
  stackoverflowId:   3828228
  linkedIn:          benjaminscabbia
  github:            benscabbia
  gitlab:            benscabbia
  #twitter:           

# Custom vars
version:             1.0.0

disqus:
  shortname: benscabbia
  
# Plugins
plugins:
  - jekyll-paginate

